ECE651-75 Order Now Button UI and Redirection
kar12thik/Online-Food-Ordering-and-Delivery-System pull request #41
Opened 2023-03-05 01:18 UTC by MareenaFr

Order Now button style changed and redirection to restaurants listing page

Test results location - Documents/General/Sprint 4/Development/ECE651-75

2023-03-05 01:30 UTC, kj8patel approved these changes
LGTM!!
Thanks for making the changes.

2023-03-05 01:57 UTC, kar12thik commented on src/components/OrderNow.js
> +          <p className="mb-3 text-white">Pellentesque eget justo eget nibh luctus semper at ut tellus.</p>
Can we put some actual text here ?

2023-03-05 02:33 UTC, kar12thik approved these changes
Changes look good.

2023-03-05 03:30 UTC, db8patel submitted a review, later dismissed
It looks nice. Test results and code changes seems perfect.

2023-03-05 03:44 UTC, itsmejay80 requested changes
When I click on Order Now it is getting redirected to the restaurant's page this is correct but not at the top of the page. Refer this for solution  https://stackoverflow.com/questions/33188994/scroll-to-the-top-of-the-page-after-render-in-react-js

2023-03-05 04:08 UTC, MareenaFr commented
> When I click on Order Now it is getting redirected to the restaurant's page this is correct but not at the top of the page. Refer this for solution https://stackoverflow.com/questions/33188994/scroll-to-the-top-of-the-page-after-render-in-react-js

Will check on this.

2023-03-05 04:58 UTC, MareenaFr commented
> When I click on Order Now it is getting redirected to the restaurant's page this is correct but not at the top of the page. Refer this for solution https://stackoverflow.com/questions/33188994/scroll-to-the-top-of-the-page-after-render-in-react-js

Made the required changes.

2023-03-05 05:01 UTC, itsmejay80 approved these changes
LGTM

2023-03-05 20:11 UTC, kj8patel approved these changes

2023-03-05 22:38 UTC, db8patel approved these changes

2023-03-06 02:54 UTC, Riya0001 approved these changes
Looks good proceed with changes

2023-03-06 03:23 UTC, kar12thik approved these changes

2023-03-06 15:48 UTC, merged